/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EdsDivider {
    'color': string;
    'variant': string;
  }
  interface MyButton {
    'color': string;
    'value': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface TestComponent {}
  interface TextField {
    'disabled': boolean;
    'helpericon': string;
    'helpertext': string;
    'label': string;
    'meta': string;
    'multiline': boolean;
    'placeholder': string;
    'type': string;
    'variant': string;
  }
}

declare global {


  interface HTMLEdsDividerElement extends Components.EdsDivider, HTMLStencilElement {}
  var HTMLEdsDividerElement: {
    prototype: HTMLEdsDividerElement;
    new (): HTMLEdsDividerElement;
  };

  interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {}
  var HTMLMyButtonElement: {
    prototype: HTMLMyButtonElement;
    new (): HTMLMyButtonElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {}
  var HTMLTestComponentElement: {
    prototype: HTMLTestComponentElement;
    new (): HTMLTestComponentElement;
  };

  interface HTMLTextFieldElement extends Components.TextField, HTMLStencilElement {}
  var HTMLTextFieldElement: {
    prototype: HTMLTextFieldElement;
    new (): HTMLTextFieldElement;
  };
  interface HTMLElementTagNameMap {
    'eds-divider': HTMLEdsDividerElement;
    'my-button': HTMLMyButtonElement;
    'my-component': HTMLMyComponentElement;
    'test-component': HTMLTestComponentElement;
    'text-field': HTMLTextFieldElement;
  }
}

declare namespace LocalJSX {
  interface EdsDivider {
    'color'?: string;
    'variant'?: string;
  }
  interface MyButton {
    'color'?: string;
    'value'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface TestComponent {}
  interface TextField {
    'disabled'?: boolean;
    'helpericon'?: string;
    'helpertext'?: string;
    'label'?: string;
    'meta'?: string;
    'multiline'?: boolean;
    'placeholder'?: string;
    'type'?: string;
    'variant'?: string;
  }

  interface IntrinsicElements {
    'eds-divider': EdsDivider;
    'my-button': MyButton;
    'my-component': MyComponent;
    'test-component': TestComponent;
    'text-field': TextField;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'eds-divider': LocalJSX.EdsDivider & JSXBase.HTMLAttributes<HTMLEdsDividerElement>;
      'my-button': LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'test-component': LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
      'text-field': LocalJSX.TextField & JSXBase.HTMLAttributes<HTMLTextFieldElement>;
    }
  }
}


